#
# This file is autogenerated during plugin quickstart and overwritten during
# plugin makedist. DO NOT CHANGE IT if you plan to use plugin makedist to update 
# the distribution.
#

from setuptools import setup, find_packages

kwargs = {'author': 'Scott E. Townsend',
 'author_email': 'scott.e.townsend@nasa.gov',
 'classifiers': ['Intended Audience :: Science/Research',
                 'Topic :: Scientific/Engineering'],
 'description': 'Component wrapper for VSP (Vehicle Sketch Pad)',
 'download_url': '',
 'entry_points': {
    "openmdao.component": [
       "vsp_wrapper.wrapper.VSP=vsp_wrapper.wrapper:VSP"
       ],
    "openmdao.container": [
       "vsp_wrapper.airfoil.Airfoil=vsp_wrapper.airfoil:Airfoil",
       "vsp_wrapper.blank.Blank=vsp_wrapper.blank:Blank",
       "vsp_wrapper.blank.BlankParms=vsp_wrapper.blank:BlankParms",
       "vsp_wrapper.cabin.CabinLayout=vsp_wrapper.cabin:CabinLayout",
       "vsp_wrapper.cabin.CabinLayoutParms=vsp_wrapper.cabin:CabinLayoutParms",
       "vsp_wrapper.cabin.CrossSection=vsp_wrapper.cabin:CrossSection",
       "vsp_wrapper.component.VSPComponent=vsp_wrapper.component:VSPComponent",
       "vsp_wrapper.duct.Duct=vsp_wrapper.duct:Duct",
       "vsp_wrapper.duct.DuctParms=vsp_wrapper.duct:DuctParms",
       "vsp_wrapper.engine.Engine=vsp_wrapper.engine:Engine",
       "vsp_wrapper.engine.EngineParms=vsp_wrapper.engine:EngineParms",
       "vsp_wrapper.external.External=vsp_wrapper.external:External",
       "vsp_wrapper.external.ExternalParms=vsp_wrapper.external:ExternalParms",
       "vsp_wrapper.fuselage.CrossSection=vsp_wrapper.fuselage:CrossSection",
       "vsp_wrapper.fuselage.Fuselage=vsp_wrapper.fuselage:Fuselage",
       "vsp_wrapper.fuselage.FuseParms=vsp_wrapper.fuselage:FuseParms",
       "vsp_wrapper.fuselage.IMLParms=vsp_wrapper.fuselage:IMLParms",
       "vsp_wrapper.fuselage.MLParms=vsp_wrapper.fuselage:MLParms",
       "vsp_wrapper.fuselage.OMLParms=vsp_wrapper.fuselage:OMLParms",
       "vsp_wrapper.fuselage2.CrossSection=vsp_wrapper.fuselage2:CrossSection",
       "vsp_wrapper.fuselage2.Fuselage2=vsp_wrapper.fuselage2:Fuselage2",
       "vsp_wrapper.fuselage2.FuseParms=vsp_wrapper.fuselage2:FuseParms",
       "vsp_wrapper.general.GeneralParms=vsp_wrapper.general:GeneralParms",
       "vsp_wrapper.geometry.VSPGeometry=vsp_wrapper.geometry:VSPGeometry",
       "vsp_wrapper.havoc.Havoc=vsp_wrapper.havoc:Havoc",
       "vsp_wrapper.havoc.HavocParms=vsp_wrapper.havoc:HavocParms",
       "vsp_wrapper.hwb.HWB=vsp_wrapper.hwb:HWB",
       "vsp_wrapper.hwb.HWBParms=vsp_wrapper.hwb:HWBParms",
       "vsp_wrapper.mesh.Mesh=vsp_wrapper.mesh:Mesh",
       "vsp_wrapper.mesh.MeshParms=vsp_wrapper.mesh:MeshParms",
       "vsp_wrapper.ms_wing.MSWing=vsp_wrapper.ms_wing:MSWing",
       "vsp_wrapper.ms_wing.MSWingParms=vsp_wrapper.ms_wing:MSWingParms",
       "vsp_wrapper.pod.Pod=vsp_wrapper.pod:Pod",
       "vsp_wrapper.pod.PodParms=vsp_wrapper.pod:PodParms",
       "vsp_wrapper.prop.Prop=vsp_wrapper.prop:Prop",
       "vsp_wrapper.prop.PropParms=vsp_wrapper.prop:PropParms",
       "vsp_wrapper.prop.SectParms=vsp_wrapper.prop:SectParms",
       "vsp_wrapper.source.BaseSource=vsp_wrapper.source:BaseSource",
       "vsp_wrapper.source.BoxSource=vsp_wrapper.source:BoxSource",
       "vsp_wrapper.source.LineSource=vsp_wrapper.source:LineSource",
       "vsp_wrapper.source.PointSource=vsp_wrapper.source:PointSource",
       "vsp_wrapper.texture.Texture=vsp_wrapper.texture:Texture",
       "vsp_wrapper.user.User=vsp_wrapper.user:User",
       "vsp_wrapper.user.UserParms=vsp_wrapper.user:UserParms",
       "vsp_wrapper.window.VirtWindow=vsp_wrapper.window:VirtWindow",
       "vsp_wrapper.wing.Wing=vsp_wrapper.wing:Wing",
       "vsp_wrapper.wing.WingParms=vsp_wrapper.wing:WingParms",
       "vsp_wrapper.wing_sect.WingSect=vsp_wrapper.wing_sect:WingSect",
       "vsp_wrapper.wrapper.VSP=vsp_wrapper.wrapper:VSP",
       "vsp_wrapper.xml_container.XMLContainer=vsp_wrapper.xml_container:XMLContainer",
       ],
       'openmdao.parametric_geometry': [
         "vsp_wrapper.parageom.VSPParametricGeometry=vsp_wrapper.parageom:VSPParametricGeometry"
       ],
       'openmdao.binpub': [
            'vsp_wrapper.parageom.VSPSender = vsp_wrapper.parageom:VSPSender'
       ]
 },
 'include_package_data': True,
 'install_requires': ['openmdao.main'],
 'keywords': ['openmdao'],
 'license': 'Apache License, Version 2.0',
 'maintainer': 'Scott E. Townsend',
 'maintainer_email': 'scott.e.townsend@nasa.gov',
 'name': 'vsp_wrapper',
 'package_data': {'vsp_wrapper': []},
 'package_dir': {'': 'src'},
 'packages': ['vsp_wrapper'],
 'url': 'https://github.com/OpenMDAO-Plugins/vsp_wrapper',
 'version': '0.7',
 'zip_safe': False
 }


setup(**kwargs)

